### ISSUE TITLE
google-tts-apiのバージョンが古いため、コマンドの実行に失敗する

### ISSUE THREAD

**Issue by MisakiFukuyo** [freddiefujiwara/google-home-speaker#5]
## 現象

コマンドを実行したところ、標準出力に何も表示されずコマンドが終了しました。

## 手元での対処

package.jsonを以下のように変更し、`npm i google-tts-api` したところ標準出力に表示されるようになり、コマンド実行が成功しました。

```
"google-tts-api": "0.0.3",
```

**Comment by freddiefujiwara** [comment]
申し訳ございません　今気づきました
version 0.0.6 で対応させていただきました
